server:
  port: 8085

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KrishnamoorthyJuttooChandrasekaran/CloudConfigServer
          clone-on-start: true
          skipSslValidation: true