server:
  port: 4002

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: FARMER-SERVICE
          uri: http://localhost:4001
          predicates:
            - Path=/farmer/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: CircuitBreaker
              args:
                  name: ADMIN-SERVICE
                  fallbackUri: forward:/farmerServiceFallBack
                  failureRateThreshold: 50
                  minimumNumberOfCalls: 10
                  waitDurationInOpenState: 5000
                  permittedNumberOfCallsInHalfOpenState: 3
                  slidingWindowSize: 10
                  recordExceptions:
                    - java.util.concurrent.TimeoutException

        - id: CUSTOMER-SERVICE
          uri: http://localhost:4000
          predicates:
            - Path=/customer/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER-SERVICE
                fallbackUri: forward:/customerServiceFallBack
                failureRateThreshold: 50
                minimumNumberOfCalls: 10
                waitDurationInOpenState: 5000
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                recordExceptions:
                  - java.util.concurrent.TimeoutException

        - id: SECURITY-SERVICE
          uri: http://localhost:4005
          predicates:
            - Path=/security/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: CircuitBreaker
              args:
                name: SECURITY-SERVICE
                fallbackUri: forward:/securityServiceFallBack
                failureRateThreshold: 50
                minimumNumberOfCalls: 10
                waitDurationInOpenState: 5000
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                recordExceptions:
                  - java.util.concurrent.TimeoutException

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka